# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-03-13 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultrecord',
            name='delete_status',
            field=models.BooleanField(default=False, verbose_name='删除状态'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='class_list',
            field=models.ManyToManyField(blank=True, to='app01.ClassList', verbose_name='已报班级'),
        ),
    ]
